model:
  provider: ollama
#  name: gpt-oss:20b
#  name: "mistral:7b-instruct"
  name: llama3:8b
  base_url: http://localhost:11434
agent:
  max_tool_calls: 5
  top_k_context: 5
  self_consistency: 3   # 合議用サンプル数
rag:
  docs_dir: ./data/docs
